apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: circleci-build-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/saiakhil46/argocd-deploy.git
    targetRevision: HEAD
    path: helm-chart/circleci-build
  destination:
    server: https://kubernetes.default.svc
    namespace: circleci-ns

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
