apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circleci-build.fullname" . }}
  labels:
    {{- include "circleci-build.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "circleci-build.selectorLabels" . | nindent 6 }}
  strategy: 
    {{- if eq .Values.replicaCount 1.0 }}
    {{- toYaml .Values.strategy1 | nindent 4}}
    {{- else }}
    {{- toYaml .Values.strategy2 | nindent 4}} 
    {{- end }} 
  template:
    metadata:
      labels:
        {{- include "circleci-build.selectorLabels" . | nindent 8 }}
    spec: 
      containers:
        - image: {{ .Values.image.repository }}
          name: {{ include "circleci-build.fullname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
      restartPolicy: {{ .Values.image.restartPolicy }}
